### ISSUE TITLE
Fix the UnicodeDecodeError in file `utils.py`

### ISSUE THREAD

**Issue by Patricky-Tau** [LaiJunBin/domjudge-code-download-tool#1]
### Current Behavior:

```py
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb5 in position 259: invalid start byte
```

### Expected Behavior:

Download all codes with various file-encodings.

### Steps To Reproduce:

Try to run `uvicorn.exe main:app` to get many files with various file-encodings.

### Environment:

- OS: Microsoft Windows 10 (with msys2)
- Python: 3.8.10

### Else

I took a look at <https://stackoverflow.com/questions/3470546/how-do-you-decode-base64-data-in-python> and fix the code in <https://github.com/LaiJunBin/domjudge-code-download-tool/blob/master/utils.py#L24#L25> into:

```py
def base64_decode(b64data):
    return base64.b64decode( base64.b64encode(b64data.encode('utf-8'))).decode('utf-8')
```

And luckily it works.

That's all. Since I'm not sure about whether it's a feature or bug, I didnot add any a tag here.

**Comment by Patricky-Tau** [comment]
Oh my... It just works during the runtime, but its output were many files after encoding.. I guess there was something wrong due to my mistakes.

The problem isn't solved yet. 😢😢

**Comment by LaiJunBin** [comment]
Sorry, I can't reproduce it. 😢 

I try to follow the steps:
1. clone the repo.
2. copy .env.example to .env and fill it.
3. run `python -m venv env` and enter the env.
4. run `pip install -r requirements.txt` to install dependents.
5. run `uvicorn main:app`
6. browse `http://localhost:8000/`
7. next, I try to download.

Snapshot:
![image](https://user-images.githubusercontent.com/26165676/196018645-9e003cab-8cb8-47b9-aae0-62a929222ff9.png)


My environment is also Windows 10 and Python 3.8.10.

I need more information to help you solve the issue.

**Comment by Patricky-Tau** [comment]
You may try this `.env` file (it's a temporary account):

```txt
***
```

Select the competition `2022 SWPU ACM-Team Try-out Contest Review` and download. There are only $28$ files now, but it didnot work..

After changing the code mentioned above, it works. After decoding with

```zsh
for j in ./*
  for i in $j/*
    cat $i | base64 -d | tee $i
```

I got all files successfully.

**Comment by LaiJunBin** [comment]
I fixed. add gb2312 for decoding.

**Comment by Patricky-Tau** [comment]
Thanks, I will change the password of the account.
